import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BotonWhatsapp from "@/components/BotonWhatsapp ";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mi Portafolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-y-scroll overflow-x-scroll`}>
        {children}
        <BotonWhatsapp/>
        </body>
    </html>
  );
}
